remote_theme: sylhare/Type-on-Strap
header_text: Welcome to my tech blog
footer_text: Copyright &copy; 2023 | Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
color_image: /assets/img/lineart.png

# PAGINATION
post_navigation: true
paginate: 5
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]


baseurl: "/"
url: "https://neilbrown.dev/"

# Podcasts
podcasts:
  -
    name: ".Net Rocks"
    link: "https://www.dotnetrocks.com/"
    description: "A long running weekly podcast about the .Net platform"
  -
    name: "Azure DevOps Podcast"
    link: "http://azuredevopspodcast.clear-measure.com/"
    description: "About making software quicker and more reliably"
